# Generated by Django 5.2.7 on 2025-10-13 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_cattegories'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
