# Generated by Django 5.2.7 on 2025-10-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_category_remove_product_cattegories_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
